### PR TITLE
solium: change style rules to warning

### PR DESCRIPTION
**Pull request by elopio**

### CODE REVIEW

**Comment by frangio** [comment]
Thanks @elopio! Can you explain a bit why this seems to be adding more rules? Are they the ones in `solium:all`?

**Comment by elopio** [comment]
I hate that json has no comments, that should be a comment on the file. :angry: 
So, yes @frangio. solium:all includes style errors, which we have to overwrite as warnings here. All the additions come from solium:all.

**Comment by elopio** [comment]
ah, except no-unused-vars, no need to overwrite that one. I wonder how it ended up here...

**Comment by frangio** [comment]
It should definitely be a comment in the file. :cry:

**Pull request merged**
